services:
  backend:
    image: matheuslameque/eijipay:latest
    ports:
      - "80:3000"
    environment:
      - DATABASE_URL=postgres://eijipay:eijipass@db:5332/eijipaydb
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: eijipaydb
      POSTGRES_USER: eijipay
      POSTGRES_PASSWORD: eijipass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
